image: node:8

# Set up MySQL test-database
services:
  - mysql:5.5

# Configure test-database
variables:
  MYSQL_DATABASE: supertestdb
  MYSQL_ROOT_PASSWORD: secret

# Install node libraries
before_script:
  - cd Server
  - npm install


# Run JEST tests
run_tests:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - Klient/coverage
      - Server/coverage

# Publish coverage report on gitlab-pages
pages:
  stage: deploy
  dependencies:
    - run_tests
  script:
    - mkdir .public
    - mkdir .public/client
    - mkdir .public/server
    - cp -r Klient/coverage .public/client
    - cp -r Server/coverage .public/server
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master


